


function E = pomdp_threebuttons_canon_setup(W)
    
    
    %% set parameters
    
    cursorSizeDeg = 0.5;
    cursorColor = [0,0,0;255,0,0;0,255,0]';
    
    telprocTau = 20;
    telprocLambdamax = 0.8;
    telprocLambdamin = 0.0;
    telProcRenewrate = 0.005;
    telprocDepleteRate = 0.4;
    
    stimTexVar = 0.2;
    stimSizeDeg = 5;
    stimWinSizeDeg = 4;
    stimWinStdDeg = 0.25;
    stimNCol = 1000;
    
    durFixSec = 0.5;
    durGapSec = 10/60;
    durStimSec = 3/60;
    durItiSec = 0.5;
    durPauseSec = 5;
    
    textSize = 32;
    textStyle = 0;
    textFont = 'Arial';
    textColor = 255;
    textFreqHz = 1;
    
    
    %% convert units
    
    cursorSizeRad = cursorSizeDeg*pi/180;
    stimSizeRad = stimSizeDeg*pi/180;
    stimWinSizeRad = stimWinSizeDeg*pi/180;
    stimWinStdRad = stimWinStdDeg*pi/180;
    
    cursorSizeCm = W.viewingDistCm*tan(cursorSizeRad);
    stimSizeCm = W.viewingDistCm*tan(stimSizeRad);
    stimWinSizeCm = W.viewingDistCm*tan(stimWinSizeRad);
    stimWinStdCm = W.viewingDistCm*tan(stimWinStdRad);
    
    cursorSizePix = cursorSizeCm/W.pixSize;
    stimSizePix = round(stimSizeCm/W.pixSize);
    stimWinSizePix = stimWinSizeCm/W.pixSize;
    stimWinStdPix = stimWinStdCm/W.pixSize;
    
    
    %% set up design
    
    nCond = 1;
    
    
    %% generate structure
    
    E = struct(...
        'nCond',                        nCond , ...
        'cursorSizeDeg',                cursorSizeDeg , ...
        'cursorSizeRad',                cursorSizeRad , ...
        'cursorSizeCm',                 cursorSizeCm , ...
        'cursorSizePix',                cursorSizePix , ...
        'cursorColor',                  cursorColor , ...
        'telprocTau',                   telprocTau , ...
        'telprocLambdamax',             telprocLambdamax , ...
        'telprocLambdamin',             telprocLambdamin , ...
        'telProcRenewrate',             telProcRenewrate , ...
        'telprocDepleteRate',           telprocDepleteRate , ...
        'stimTexVar',                   stimTexVar , ...
        'stimSizeDeg',                  stimSizeDeg , ...
        'stimSizeRad',                  stimSizeRad , ...
        'stimSizeCm',                   stimSizeCm , ...
        'stimSizePix',                  stimSizePix , ...
        'stimWinSizeDeg',            	stimWinSizeDeg , ...
        'stimWinSizeRad',             	stimWinSizeRad , ...
        'stimWinSizeCm',                stimWinSizeCm , ...
        'stimWinSizePix',               stimWinSizePix , ...
        'stimWinStdDeg',                stimWinStdDeg , ...
        'stimWinStdRad',                stimWinStdRad , ...
        'stimWinStdCm',                 stimWinStdCm , ...
        'stimWinStdPix',                stimWinStdPix , ...
        'stimNCol',                     stimNCol, ...
        'durFixSec',                    durFixSec , ...
        'durGapSec',                    durGapSec , ...
        'durStimSec',                   durStimSec , ...
        'durItiSec',                    durItiSec , ...
        'durPauseSec',                  durPauseSec , ...
        'textSize',                     textSize , ...
        'textStyle',                    textStyle , ...
        'textFont',                     textFont , ...
        'textColor',                    textColor , ...
        'textFreqHz',                   textFreqHz ...
        );
    
    
end


